# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/movie-8',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/movie-8',
                'lib_path': 'movie_8'},
  'syms': {'movie_8.core': {'movie_8.core.foo': ('core.html#foo', 'movie_8/core.py')}}}